[package]
name = "s3-server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# TODO feature gate these to shrink the build size
async-trait = "0.1"
hyper = { version = "0.14", features = ["full"] }
s3s = "0.5"
tokio = { version = "1", features= ["full"]}